---

- hosts: linux-workstation
  become: false

  vars:
    atom_packages:
      - linter
      - linter-js-yaml
      - linter-jsonlint
      - pretty-json
      - script
      - expand-region
      - split-diff
      
      - project-view
      - tree-view-git-status
      - git-plus
      - git-diff-details
      - git-blame
      - hyperclick
      - hyperlink-hyperclick
      - symbols-tree-view

  roles:
    - { role: jgkim.atom, atom_upgrade_all: true }

  tasks:
    - blockinfile:
        dest: ~/.atom/keymap.cson
        marker: '# {mark} ANSIBLE MANAGED BLOCK for user-atom playbook'
        create: true
        block: |
          'atom-text-editor':
            'alt-up': 'expand-region:expand'
            'alt-down': 'expand-region:shrink'
