---

- hosts: linux-workstation
  become: false

  vars:
    atom_packages:
      - language-docker
      - linter-docker
      - dockerletion

  roles:
    - { role: jgkim.atom, atom_upgrade_all: true }
